# Generated by Django 4.1.7 on 2023-02-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus_nme',
            new_name='campus_name',
        ),
    ]
